//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prison.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prison.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paints a huge portrait of the warden using toothpaste!.
        /// </summary>
        public static string ArtistCrazy {
            get {
                return ResourceManager.GetString("ArtistCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is studying art history from old magazines..
        /// </summary>
        public static string ArtistStudy {
            get {
                return ResourceManager.GetString("ArtistStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too tired to create madness..
        /// </summary>
        public static string ArtistTired {
            get {
                return ResourceManager.GetString("ArtistTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is painting the cafeteria walls..
        /// </summary>
        public static string ArtistWork {
            get {
                return ResourceManager.GetString("ArtistWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisoner name cannot be empty!.
        /// </summary>
        public static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New arrival: {0}.
        /// </summary>
        public static string LogArrival {
            get {
                return ResourceManager.GetString("LogArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not want to study!.
        /// </summary>
        public static string LogNoStudy {
            get {
                return ResourceManager.GetString("LogNoStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot work!.
        /// </summary>
        public static string LogNoWork {
            get {
                return ResourceManager.GetString("LogNoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was transferred to another prison..
        /// </summary>
        public static string LogRemoved {
            get {
                return ResourceManager.GetString("LogRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is staring at the wall. Energy: {1}/100..
        /// </summary>
        public static string NormalAction {
            get {
                return ResourceManager.GetString("NormalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lectures the guards about freedom. The guards are shocked..
        /// </summary>
        public static string PhilCrazy {
            get {
                return ResourceManager.GetString("PhilCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is reading Nietzsche in the library..
        /// </summary>
        public static string PhilStudy {
            get {
                return ResourceManager.GetString("PhilStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is resting in the cell. Energy: {1}/100..
        /// </summary>
        public static string RestAction {
            get {
                return ResourceManager.GetString("RestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} panics and tries to escape through the vent, but gets stuck!.
        /// </summary>
        public static string RookieCrazy {
            get {
                return ResourceManager.GetString("RookieCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is mopping the floor. Very tired..
        /// </summary>
        public static string RookieWork {
            get {
                return ResourceManager.GetString("RookieWork", resourceCulture);
            }
        }
    }
}
